# Generated by Django 4.0.1 on 2022-03-21 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Post title')),
                ('content', models.TextField(verbose_name='Post content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Post created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Post updated')),
                ('image', models.ImageField(upload_to=post.models.Post.file_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Post author')),
                ('cat', models.ManyToManyField(related_name='posts', to='post.Category')),
            ],
            options={
                'verbose_name': 'Post',
                'db_table': 'posts',
            },
        ),
    ]
