# Generated by Django 4.0.1 on 2022-03-23 11:26

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=post.models.Post.file_path, upload_to=post.models.Post.file_path),
        ),
    ]
