# Generated by Django 4.0.1 on 2022-03-23 11:29

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='photos/2022/03/23/00000001', upload_to=post.models.Post.file_path),
        ),
    ]
