# Generated by Django 4.0.1 on 2022-03-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(unique=True, verbose_name='Title news')),
                ('href', models.TextField(unique=True)),
            ],
            options={
                'verbose_name': 'New',
                'db_table': 'news',
            },
        ),
    ]
